//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryCard_GameLatHinh_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameCard()
        {
            this.Moves = new HashSet<Move>();
            this.Moves1 = new HashSet<Move>();
        }
    
        public int GameCardID { get; set; }
        public int GameID { get; set; }
        public int DictID { get; set; }
        public int Position { get; set; }
        public bool IsRevealed { get; set; }
        public bool IsMatched { get; set; }
    
        public virtual CardDictionary CardDictionary { get; set; }
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Move> Moves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Move> Moves1 { get; set; }
    }
}
