//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryCard_GameLatHinh_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.GameCards = new HashSet<GameCard>();
            this.Moves = new HashSet<Move>();
        }
    
        public int GameID { get; set; }
        public int PlayerID { get; set; }
        public int LevelID { get; set; }
        public int Score { get; set; }
        public int TotalMoves { get; set; }
        public int TotalMatches { get; set; }
        public string GameStatus { get; set; }
        public int Stars { get; set; }
        public int RewardCoins { get; set; }
        public int RewardExp { get; set; }
        public int TimeSpent { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameCard> GameCards { get; set; }
        public virtual Level Level { get; set; }
        public virtual Player Player { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Move> Moves { get; set; }
    }
}
