//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryCard_GameLatHinh_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int LoginID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int PlayerID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
