//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryCard_GameLatHinh_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GameLatHinhEntities : DbContext
    {
        public GameLatHinhEntities()
            : base("name=GameLatHinhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievements { get; set; }
        public virtual DbSet<CardDictionary> CardDictionaries { get; set; }
        public virtual DbSet<GameCard> GameCards { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Move> Moves { get; set; }
        public virtual DbSet<PlayerAchievement> PlayerAchievements { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<vw_Leaderboard> vw_Leaderboard { get; set; }
    
        public virtual int SP_CapNhatThanhTuu(Nullable<int> playerID, Nullable<int> achievementID, Nullable<int> progressToAdd)
        {
            var playerIDParameter = playerID.HasValue ?
                new ObjectParameter("PlayerID", playerID) :
                new ObjectParameter("PlayerID", typeof(int));
    
            var achievementIDParameter = achievementID.HasValue ?
                new ObjectParameter("AchievementID", achievementID) :
                new ObjectParameter("AchievementID", typeof(int));
    
            var progressToAddParameter = progressToAdd.HasValue ?
                new ObjectParameter("ProgressToAdd", progressToAdd) :
                new ObjectParameter("ProgressToAdd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CapNhatThanhTuu", playerIDParameter, achievementIDParameter, progressToAddParameter);
        }
    
        public virtual int SP_KetThucVanChoi(Nullable<int> gameID, Nullable<bool> isWin, Nullable<int> timeSpent, Nullable<int> totalMoves, Nullable<int> baseScore)
        {
            var gameIDParameter = gameID.HasValue ?
                new ObjectParameter("GameID", gameID) :
                new ObjectParameter("GameID", typeof(int));
    
            var isWinParameter = isWin.HasValue ?
                new ObjectParameter("IsWin", isWin) :
                new ObjectParameter("IsWin", typeof(bool));
    
            var timeSpentParameter = timeSpent.HasValue ?
                new ObjectParameter("TimeSpent", timeSpent) :
                new ObjectParameter("TimeSpent", typeof(int));
    
            var totalMovesParameter = totalMoves.HasValue ?
                new ObjectParameter("TotalMoves", totalMoves) :
                new ObjectParameter("TotalMoves", typeof(int));
    
            var baseScoreParameter = baseScore.HasValue ?
                new ObjectParameter("BaseScore", baseScore) :
                new ObjectParameter("BaseScore", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KetThucVanChoi", gameIDParameter, isWinParameter, timeSpentParameter, totalMovesParameter, baseScoreParameter);
        }
    }
}
