//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryCard_GameLatHinh_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move
    {
        public int MoveID { get; set; }
        public int GameID { get; set; }
        public Nullable<int> MoveNumber { get; set; }
        public int Card1ID { get; set; }
        public int Card2ID { get; set; }
        public Nullable<bool> IsMatch { get; set; }
        public System.DateTime MoveTime { get; set; }
    
        public virtual GameCard GameCard { get; set; }
        public virtual GameCard GameCard1 { get; set; }
        public virtual Game Game { get; set; }
    }
}
