//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryCard_GameLatHinh_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerAchievement
    {
        public int PlayerID { get; set; }
        public int AchievementID { get; set; }
        public int CurrentProgress { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> UnlockedDate { get; set; }
    
        public virtual Achievement Achievement { get; set; }
        public virtual Player Player { get; set; }
    }
}
