//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryCard_GameLatHinh_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Leaderboard
    {
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public int ProfileLevel { get; set; }
        public int TotalExp { get; set; }
        public int HighScore { get; set; }
        public int HighestGameLevel { get; set; }
        public int TotalWins { get; set; }
        public Nullable<double> WinRate { get; set; }
    }
}
